version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.4.0
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - spaced_ace_network
  llm-api:
    build:
      context: ./llm-api/
    environment:
      MODEL: ${MODEL}
      BASE_URL: ${BASE_URL}
      API_KEY: ${API_KEY}
      PROVIDER: ${PROVIDER}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PW}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - spaced_ace_network
  frontend:
    build:
      context: ./frontend/
    environment:
      - BACKEND_URL=http://backend:80
      - PORT=80
    ports:
      - "80:80"
    networks:
      - spaced_ace_network
  backend:
    build:
      context: ./backend/
    environment:
      LLM_API_URL: http://llm-api:80
      PORT: 80
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PW}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: postgres
      RESEND_API_KEY: ${RESEND_API_KEY}
    restart: on-failure
    depends_on:
      - database
      - llm-api
    ports:
      - "9000:80"
    networks:
      - spaced_ace_network
  database:
    platform: linux/amd64
    build:
        dockerfile: ./Dockerfile
        context: ./postgres/
    image: spacedace/postgres:0.0.1
    container_name: spacedace_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # can only create extensions in db postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - spacedace-db:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - spaced_ace_network

volumes:
  ollama:
  spacedace-db:

networks:
  spaced_ace_network:
    driver: bridge

